<div style="border: 1px #ebebeb solid; background: #f5f5f5; padding: 30px; padding-bottom: 20px;">
    <form role="form">
        <div class="form-group">
            <label for="shortUrl">&nbsp;</label>
            <input type="text" id="shortUrl" class="form-control"
                   data-trigger="focus" data-toggle="tooltip" data-placement="top" title="Press Ctrl+C to copy"
                   value="<?=$urlInfo->getShortUrl()?>"
                   style="text-align: center; width: 300px; height: 45px; cursor: default;
                           border: 1px #e5e5e5 solid; background: #f9f9f9;
                           font-size: 21px; font-weight: bold; color: #15c;"
                   readonly="readonly"
                >
        </div>
    </form>

    <div>
        <?=$urlInfo->getInsertedAgo()?> - <a href="#">details</a>
    </div>
    <div style="margin-top: 5px;">
        <a href="<?=$urlInfo->getLongUrl()?>" target="_blank"><?=$urlInfo->getLongUrl()?></a>
    </div>
    <div style="margin-top: 5px; min-height: 100px; max-height: 500px; width; 300px; overflow: hidden;">
        <img src="<?=$urlInfo->getPreviewUrl()?>" />
    </div>
</div>
