<footer class="footer" style="background: #bac3c7;">
    <div class="container text-center">
        <i class="fa fa-heart"></i>
        <font style="color: #999; font-size: 14px;">
            <b>old <a href="http://old.smdmitry.ru" class="smdmitry" title="old sm.dmitry website"><font style="color: #FF9900;">sm</font><font style="color: #CCCCCC;">.</font><font style="color: #333333;">dmitry</font></a> website</b>
        </font>
    </div>
</footer>

<? /*<footer class="footer">
    <div class="container text-center">
        <font style="color: #CCCCCC; font-size: 10px;">
            <b>© 2005-2008 <a href="http://old.smdmitry.ru" class="smdmitry" title="дизайн и верстка: sm.dmitry"><font style="color: #FF9900;">sm</font><font style="color: #CCCCCC;">.</font><font style="color: #333333;">dmitry</font></a></b>
        </font>

        <small class="copyright">
            <i class="fa fa-heart"></i> <a href="http://smdmitry.com" target="_blank">Smirnov Dmitry</a>
        </small>
    </div>
</footer>*/ ?>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56164151-1', 'auto');
  ga('send', 'pageview');
</script>

<script type="text/javascript">
    /*var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-56164151-1']);
    _gaq.push(['_trackPageLoadTime']);

    $(window).load(function(){
        var ga = document.createElement('script'); ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    });*/
</script>

<script type="text/javascript">
$(window).load(function(){
  new Image().src = "http://counter.yadro.ru/hit;smdmitry.com?r"+escape(document.referrer)+((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+";"+Math.random();
});
</script>

<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//smdmitry.com/analytics/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//smdmitry.com/analytics/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>

</body>
</html>
