<? include 'header_base.phtml' ?>

<header class="header">
    <div class="container">
        <a href="/"><img class="profile-image img-responsive pull-left" src="/static/images/profile.png" alt="Smirnov Dmitry" /></a>
        <div class="profile-content pull-left">
            <h1 class="name">Smirnov Dmitry</h1>
            <h2 class="desc">Web App Developer</h2>
            <ul class="social list-inline">
                <li class="last-item"><a href="http://ru.linkedin.com/in/smdmitry/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                <?php /*<li class="last-item"><a href="#"><i class="fa"><strong>hh</strong></i></a></li>*/ ?>
            </ul>
        </div>
        <a class="btn btn-cta-primary pull-right" href="https://www.linkedin.com/profile/view?id=175140645" target="_blank"><i class="fa fa-paper-plane"></i> Contact Me</a>
    </div>
</header>
