<!DOCTYPE html>
<html>
<head>
    <title>smdmitry.com</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css">
    <link id="theme-style" rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/base.css">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript" src="/static/plugins/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="/static/plugins/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/plugins/jquery-rss/dist/jquery.rss.min.js"></script>
    <script type="text/javascript" src="/static/js/main.js"></script>
</head>

<body>

<header class="header">
    <div class="container">
        <a href="/"><img class="profile-image img-responsive pull-left" src="/static/images/profile.png" alt="Smirnov Dmitry" /></a>
        <div class="profile-content pull-left">
            <h1 class="name">Smirnov Dmitry</h1>
            <h2 class="desc">Web App Developer</h2>
            <ul class="social list-inline">
                <li class="last-item"><a href="http://ru.linkedin.com/in/smdmitry/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                <?php /*<li class="last-item"><a href="#"><i class="fa"><strong>hh</strong></i></a></li>*/ ?>
            </ul>
        </div>
        <a class="btn btn-cta-primary pull-right" href="https://www.linkedin.com/profile/view?id=175140645" target="_blank"><i class="fa fa-paper-plane"></i> Contact Me</a>
    </div>
</header>
