<!DOCTYPE HTML>
<html>
<head>
    <title>Autosms</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script type='text/javascript' charset='utf-8'>
        window.addEventListener('load', function(e) {
            setTimeout(function() { window.scrollTo(0, 1); }, 100);
        }, false);
    </script>

    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimal-ui" />
    <meta name="apple-mobile-web-app-title" content="Autosms" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="apple-touch-icon" href="/static/mobile/apple-touch-icon.png" />

    <link rel="stylesheet" href="/static/mobile/flatui/jquery.mobile.flatui.min.css" />
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

    <!-- Prevent text size change on orientation change. -->
    <style>
        html {
            -webkit-text-size-adjust: 100%;
        }
    </style>
</head>
<body>
<div data-role="page" data-quicklinks="true">
    <?=$this->getContent()?>
</div>
</body>
</html>

