<? include 'elements/header_smdmitry.phtml' ?>

<div class="container sections-wrapper">
<div class="row">
<div class="primary col-md-8 col-sm-12 col-xs-12">
    <section class="about section">
        <div class="section-inner">
            <h2 class="heading">Summary</h2>
            <div class="content">
                <p>A senior level web developer with experience in designing, developing, and managing web applications. Solid background in the development cycle of web applications, including design specifications, prototyping, interface development, testing, and ongoing maintenance.</p>

                <p>
                    <ul>
                        <li>Over 7 years experience in web application development using LAMP stack.</li>
                        <li>Experience in designing, implementing, and maintaining high traffic websites with emphasis on security, performance, and scalability.</li>
                        <li>Strong skills in Object-Oriented and MVC practices.</li>
                        <li>Experience in an agile environment.</li>
                        <li>Result-driven and deadline oriented.</li>
                        <li>Experience in team leadership and product management.</li>
                        <li>MS in Math and Computer Sciences.</li>
                    </ul>
                </p>
            </div>
        </div>
    </section>

    <section class="experience section">
        <div class="section-inner">
            <h2 class="heading">Work Experience</h2>
            <div class="content">
                <div class="item">
                    <h3 class="title">Senior Software Developer & Tech Lead - <span class="place"><a href="http://fotostrana.ru/" target="_blank">FotoStrana</a></span> <span class="year">(August 2008 - Present)</span></h3>
                    <p>
                        <p>fotostrana.ru is a Russian social network with 1.5M DAU and 5M MAU.</p>

                        <p>Started here as an intern and made it to technical lead, proposing, designing and developing core features of the product, high load social services, and internal tools for developers. Since I worked here almost from a start-up company, I managed to build many things from scratch.</p>

                        <p>As a software engineer:</p>
                        <ul>
                            <li>Developed several developer and infrastructure tools: profiling php, mysql, memcached requests, application servers monitoring.</li>
                            <li>Had experience being a Release Engineer and developed release management and code deployment tools with release rollback (deploying PHP code from SVN to 100+ application servers in seconds, later migrated to GIT).</li>
                            <li>Designed and developed mailing system capable of sending over 10M emails daily with monitoring delivery rates, CTR, links checking.</li>
                            <li>Developed tool for product managers to send promotion emails to our users filtered by different criteria.</li>
                            <li>Developed PHP backend for notifications system, including API for in-house developers and external applications.</li>
                            <li>Designed and developed standalone social apps for major social networks (Facebook, vk.com, odnoklassniki, mail.ru).</li>
                            <li>Did lots of refactoring and optimizations in different modules</li>
                            <li>Developed features like:</li>
                            <li>Importing photos and posts to user’s newsfeed from Facebook and vk.com.</li>
                            <li>Signup with Facebook or vk.com account.</li>
                            <li>User privacy system.</li>
                            <li>Friends birthdays calendar with reminders.</li>
                        </ul>

                        <p>As a tech lead:</p>
                        <ul>
                            <li>Product manager and lead developer of “Daily photo contest”, which is on the main page of fotostrana.ru.</li>
                            <li>Interviewed and hired software developer candidates to my team</li>
                            <li>Organized a training course for new developers. Trained and couched newbie developers, some of them are seniors now.</li>
                            <li>Spoken at several conferences about software development (BitByte, #HPC, DEV {highload}) with a presentation about Fotostrana architecture.</li>
                        </ul>
                    </p>
                </div>
                <div class="item">
                    <h3 class="title">QA Engineer - <span class="place"><a href="http://www.soft-consult.ru/" target="_blank">Soft-Consult</a></span> <span class="year">(April 2007 - September 2007)</span></h3>
                    <p>
                        <ul>
                            <li>Writing Software Requirements Specifications (SRS)</li>
                            <li>Writing Master Test Plan (MTP)</li>
                            <li>Testing Software</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </section>
</div>
<div class="secondary col-md-4 col-sm-12 col-xs-12">
    <aside class="info aside section">
        <div class="section-inner">
            <h2 class="heading sr-only">Basic Information</h2>
            <div class="content">
                <ul class="list-unstyled">
                    <li><i class="fa fa-map-marker"></i><span class="sr-only">Location:</span>St. Petersburg, Russia</li>
                    <?php /*<li><i class="fa fa-envelope-o"></i><span class="sr-only">Email:</span><a href="#">mail@smdmitry.com</a></li>*/ ?>
                    <li><i class="fa fa-link"></i><span class="sr-only">Website:</span><a href="http://www.smdmitry.com">http://www.smdmitry.com</a></li>
                </ul>
            </div>
        </div>
    </aside>

    <aside class="skills aside section">
        <div class="section-inner">
            <h2 class="heading">Skills</h2>
            <div class="content">
                <p class="intro">
                    <strong>Leadership</strong>: Team Lead, Release Management, Project Management, Architect.<br/>
                    <strong>Technical</strong>: PHP, Javascript, jQuery, HTML/CSS, MySQL, Memcached, NoSQL, SVN, GIT, Linux.
                </p>

                <div class="skillset">
                    <div class="item">
                        <h3 class="level-title">PHP Backend Development, SQL Tuning<span class="level-label">Expert</span></h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="100%">
                            </div>
                        </div>
                    </div>

                    <div class="item">
                        <h3 class="level-title">HTML & JS<span class="level-label">Expert</span></h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="95%">
                            </div>
                        </div>
                    </div>

                    <div class="item">
                        <h3 class="level-title">High Availability, Load Balancing, Scalability, Monetization, Couching<span class="level-label">Pro</span></h3>
                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="90%">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </aside>
</div>
</div>
</div>

<? include 'elements/footer.phtml' ?>